# Generated by Django 5.1.7 on 2025-03-09 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_well_delete_projectdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='well',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='well',
            name='well_name',
        ),
    ]
