# Generated by Django 5.1.7 on 2025-03-09 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_projectmanager_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operation',
            old_name='operation_country',
            new_name='operation_location',
        ),
    ]
