# Generated by Django 5.1.7 on 2025-03-09 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_rename_operation_country_operation_operation_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='operation_location',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='operation_name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='operation_name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_manager',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='projectmanager',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='projectmanager',
            name='last_name',
        ),
    ]
